### ISSUE TITLE
4. Update number and share of public-school children who are ever homeless during the school year

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#203]
Pillar: Opportunity-Rich & Inclusive Neighborhoods
Predictor: Housing Stability
Metric: Number and share of public-school children who are ever homeless during the school year

- [ ] Rename to `count_homeless`, `share_homeless`, `count_homeless_lb`, `count_homeless_ub`, `homeless_quality`
- [ ] Add 2020 & 2021 data
- [ ] Add subgroup: Race/ethnicity (same as SY2019-2020)

**Comment by cdsolari** [comment]
This summarizes our conversation from 2/5/24: 
1. The online data source location has been moved. It is unclear why this has occurred. But, based on national published reports, it appears as though SY2020-21 and SY2021-22 are available. Pull data for both of those if possible. 
2. Given the new file location online, we hope that the data/variable names haven't changed and there are no methodological changes. We know that the pandemic might have thrown some things off, so let's see what we can get. If it doesn't make sense to calculate for SY2020-2021, then let's not do it. We also don't know if schools were able to continue collecting homeless student data by race/ethnicity (Black NH, Hispanic, other races & ethnicities, White NH), so please check for that. They only started collecting in SY2019-20. 
3. The final files you will produce are 4: (1) county overall (2) county subgroups, (3) city overall, (4) city subgroups. 
4. No need to pull in all the prior years of data back to 2014. Just calculate for the newest years available since SY2019. You already calculated the metric for city and county back to 2014. However, for the subgroups, race/ethnicity only just became available for 2019 (SY2019-20), and although you already calculated that, we decided to revise the denominator because the shares are SUPER small. It is more helpful for a user to see disparities by race/ethnicity when the denominator is total homeless students. So, the % of all the racial/ethnic groups should sum to 100%. For example, for Black NH, it is Black, NH homeless students/all homeless students. 
5. Note: we only have lower/upper bound values around the count of homeless students. I think in this context, it makes sense, especially because we are altering the denominator of the share homeless by race. The key is to make sure we still have the share homeless overall to keep the same denominator that we have had in the past. 

Please let me know if anything is unclear! Thanks!

**Comment by cdsolari** [comment]
Currently, It looks like the new data is missing a variable that was used in the previous years of creating the metric.. We are working to see how critical this variable is. 

We also used to have a single data quality index value for both the count homeless and share homeless. We need to have two separate quality flags. Those variable names should be "count_homeless_quality" and share_homeless_quality."

**Comment by ekgutierrez1** [comment]
Raw data is now posted on [EdDataExpress ](https://eddataexpress.ed.gov/download/data-library) instead of [EdFacts](https://www2.ed.gov/about/inits/ed/edfacts/data-files/school-status-data.html). The data posted on EdDataExpress does not include the subgrant_status variable. According to EdFacts documentation, the variable is used to determine suppression information through 2018-19, and is therefore used in our own suppression determinations for data up through 2018-19. Starting in 2019-20, subgrant_status is no longer used to determine suppression information, and is therefore not necessary for this or future updates.

**Comment by ekgutierrez1** [comment]
1. It was requested that we change the denominator of the race/ethnicity variables. For example, to calculate the share of white homeless students, we now use "total homeless"  instead of "total white students enrolled" as the denominator. Therefore, I have recalculated this for SY 2019-20, as well as brought in new data for SY 2020-21 & SY 2021-22. Because of this change, we no longer use enrollment by race/ethnicity from the Common Core of Data. 
2. For cities with fewer than 10 total homeless students, subgroup counts, lower and upper bounds, quality, and share variables are designated "NA." For subgroup measures with homeless counts between 10 and 30, their data quality flags are set equal to 3.
3. We created a data share quality variable equal to the count quality variable, since both rely on the quality of the numerator.

**Comment by ekgutierrez1** [comment]
County level data for CT is unavailable for 2020 and 2021 due to mismatched county fips codes.

**Comment by awunderground** [comment]
PR is #281

**Comment by awunderground** [comment]
Closed with #281

**Comment by cdsolari** [comment]
In reviewing the subgroups file, it is clear that the race groups are not adding up to the "All" value. I expect some of that, but I noticed cases where it was over half missing in the subgroups, and that leads to a misleading distribution. We decided to assign the subgroups as NA if >30% of the total (or "All") is missing through the summation of the subgroup categories. The All will still be shown, but the distribution of the subgroups would not. In looking further, we also noticed that we had really small cell sizes shown. The raw data has rules of suppression where school districts have 0-2 homeless students, they suppress it (and the next smallest homeless count). Because we aggregate school districts to cities/counties, we have an imputation of suppressed schools set to the value of 1. And, we adjust the lower and upper bound based off of the suppression rule. In looking at the final data, we have scenarios where the entire city has just one homeless student, we decided to apply the same 0-2 count suppression rule to any cell - the overall count or for the subgroups. If any cell is 0-2,then we assign NA to the count and the share, and the quality and the lower/upper bounds.
