### ISSUE TITLE
5. Add ratio of population per primary care physician

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#204]
- [ ] Rename to `ratio_population_pc_physician`.
- [ ] Add sex for numerator and denominator

**Comment by vpancini** [comment]
I checked our data against the latest version of County Health Rankings. Our number of physicians matched, but the ratio did not. This tells me that we are using different sources of population. County Health Rankings does not include their population count in their data, but their documentation online indicates they use “Census Population Estimates” from 2021. I tried to back out their population count two ways using their ratio and their rate per 100,000. Neither matched the 2021 population count from our AHRF data, which is supposedly from the 2021 Population Estimates Program (PEP). I then brought in the raw 2021 county-level PEP population data. This didn’t match the 2021 AHRF population data that we use to create the metric OR either of the population counts I imputed for CHR. I checked the AHRF population data for other years and they all seemed to match the raw PEP population counts. Only 2021 is inconsistent.

**Comment by vpancini** [comment]
> I checked our data against the latest version of County Health Rankings. Our number of physicians matched, but the ratio did not. This tells me that we are using different sources of population. County Health Rankings does not include their population count in their data, but their documentation online indicates they use “Census Population Estimates” from 2021. I tried to back out their population count two ways using their ratio and their rate per 100,000. Neither matched the 2021 population count from our AHRF data, which is supposedly from the 2021 Population Estimates Program (PEP). I then brought in the raw 2021 county-level PEP population data. This didn’t match the 2021 AHRF population data that we use to create the metric OR either of the population counts I imputed for CHR. I checked the AHRF population data for other years and they all seemed to match the raw PEP population counts. Only 2021 is inconsistent.

We decided we should reach out to county health rankings to see if there is a reason they used the population data they did and let them know we are producing similar metrics with slightly different numbers.

**Comment by awunderground** [comment]
PR is #278

**Comment by awunderground** [comment]
PR is #284

**Comment by cdsolari** [comment]
Note that in cases where no primary care physicians are servicing the area, this should show as population#:0 rather than just zero. If this would be a substantial change, please raise that so we can consider another solution. Note that for 2019, we have some cases where we have a value for the metric, but the data quality is 'NA.' It is unclear why this might be. It may be that some very rural counties do not have a primary care physician that is measured by the data source and that is legitimate. I see we do have some zero values where data quality is strong (=1) while others are NA. We also have two cases where the value is 1589 to 1 primary care, and the data quality is NA. Can you please double-check the calculation for quality?

**Comment by awunderground** [comment]
Closed with #278
