### ISSUE TITLE
17. Update average per-grade change in English Language Arts achievement, between third and eighth grades

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#215]
Pillar: High-Quality Education
Predictor: Effective Public Education
Metric: Average per-grade change in ELA achievement between 3rd  and 8th grades

- [x] Rename to `rate_learning`, `rate_learning_lb`, `rate_learning_ub`, and `rate_learning_quality`
- [ ] Add gender subgroup - Gender no longer available
- [ ] Drop income subgroup
- [ ] Add 2018 data

**Comment by cdsolari** [comment]
The metric lead expressed an interest in changing the name of the variable to achievement_change since they aren't really growth estimates. He will be asking other experts to see for their opinion. But, as of now, the metric is calculated as well as the upper and lower bounds and the data quality flag. I encourage that this metric be submitted for review, knowing that the variable naming is still in question. Please clarify if the income subgroup was removed and the gender subgroup added. We should also still have the race/ethnicity subgroup.

**Comment by cdsolari** [comment]
Note that we need to standardize our variable names. This will have to be rate_learning, rate_learning_lb, rate_learning_ub, and rate_learning_quality. We give each metric a prefix that reflects the nature of figure (e.g., rate, share, ratio), and we allow for suffixes to indicate lower/upper bounds and the quality indicator. It is important to keep the assigned variable names because our web developer is programming these to map to the data dashboard.

**Comment by awunderground** [comment]
PR is #270

**Comment by awunderground** [comment]
The data do not support our planned analysis. We are reverting to the earlier years of data.
