### ISSUE TITLE
18. Update share of students attending high poverty schools, by student race/ethnicity

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#216]
Pillar: High-Quality Education
Predictor: School Economic Diversity
Metric: Share of students attending high-poverty schools, by student race or ethnicity

- [x] Rename to `meps20_black`, `meps20_black_quality`, `meps20_hispanic`, `meps20_hispanic_quality`, `meps20_white`, `meps20_white_quality`
- [ ] Add 2019 data

Needs a new name to align with variable names

**Comment by cdsolari** [comment]
After your initial technical review, please plan to rename the variables so that they have a "share_" prefix. For example "share_meps20_black", etc. Have that for the quality metrics too (e.g., "share_meps20_black_quality"). This is in line with our metrics having the type of figure as the prefix (e.g., ratio_, share_, rate_), and the relevant suffixes for metrics (e.g., _quality).

**Comment by awunderground** [comment]
PR is #289

**Comment by awunderground** [comment]
Closed with #289
