### ISSUE TITLE
25. Add number of deaths due to injury per 100,000 population

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#223]
Rename to `rate_injury_death`, `rate_injury_death_lb`, `rate_injury_death_ub`, and `rate_injury_death_quality`

**Comment by vpancini** [comment]
There is a CDC WONDER API available, but you can only query data at the national level with it. Because we want county-level counts, we have to download the data manually.

**Comment by vpancini** [comment]
We are using the Underlying Cause of Death by Single-Race Categories for the most recent year (2021 this year) and Underlying Cause of Death by Bridged-Race Categories for past years (2014-2020) from CDC WONDER. The Bridged-Race data (2014-2020) have both crude mortality rates and age-adjusted mortality rates, but the Single-Race data (2021) only has crude rates available at the county level. Age-adjusted rates are not available at the county level for analysis of mortality by Single Race because the populations are weighted to the 10-year age groups, and county level population estimates are not available for the "<1 year" and "1-4 years" age categories. **We need to decide whether we want to use the crude rate for all years, or use the age-adjusted rate for 2014-2020 and only use the crude rate for 2021. We could also create the measure with both the crude rates and age-adjusted rates (for the years that age-adjusted rate is available).**

**Comment by awunderground** [comment]
PR is #271

**Comment by awunderground** [comment]
Closed with #271
