### ISSUE TITLE
26. Ratio of home values owned by heads of households of a certain race to the number of heads of households of that race

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#224]
Pillar: Rewarding Work
Predictor: Wealth-Building Opportunities
Metric: Ratio of the share of a community’s housing wealth held by a racial or ethnic group to the share of households of the same group

- [x] Rename to `ratio_black_nh_house_value_households`, `ratio_hispanic_house_value_households`, `ratio_other_nh_house_value_households`, `ratio_white_nh_house_value_households`, `ratio_black_nh_house_value_households_quality`, `ratio_hispanic_house_value_households_quality`, `ratio_other_nh_house_value_households_quality`, `ratio_white_nh_house_value_households_quality`
- [x] Add 2022 data
- [x] Add Age subgroup (max 2 groups) - Jung Choi suggested age 45 as the split, so something like <age 45 and 45+

**Comment by malcalakovalski** [comment]
Flagging that replicating the data pull but with an API call to IPUMS (the original code reads in a large csv) has been a blocker so far. Once I figure this out, I expect updating the metric won't be too difficult.

**Comment by awunderground** [comment]
Is your attempt on GitHub? JP and I can offer suggestions since we've done this a few times.

**Comment by malcalakovalski** [comment]
Not yet but I'll flag as soon as I push this commit. Thank you for offering to help!

**Comment by awunderground** [comment]
PR is #284

**Comment by cdsolari** [comment]
On 3/4/24, the web developers requested that rather than display the final metric values as a ratio of two percentages with the % symbol, so simplify the character variable that removes the % character and displays the percentages instead as values between 0 and 1 with a leading zero. So, for example, instead of "89.3%:82.1%" this would display as "0.893:0.821." We ask this because the web developer will have to display these figures in different ways, and this will reduce the amount of error in displaying figures for the Dashboard.

**Comment by awunderground** [comment]
Closed with #284
